CREATE DATABASE CAFE;

use CAFE
--drop database cafe


CREATE TABLE ROLE
(
ID INT NOT NULL IDENTITY,
POSITION VARCHAR(60) not null,
salary int not null,
PRIMARY KEY(ID)
)

DROP TABLE EMPLOYEE

CREATE TABLE EMPLOYEE
(
ID INT NOT NULL identity(12345,55),
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
gender varchar(7)NOT NULL,
AGE TINYINT NOT NULL,
DATE_OF_EMPLOYMENT DATE DEFAULT GETDATE(),
ROLE_ID INT NOT NULL, 
password varchar(20),
CONTRAT_TYPE VARCHAR(60) DEFAULT 'FULL TIME',
PRIMARY KEY(ID),
CONSTRAINT FK_EMPLOYEE_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
)



CREATE TABLE SERVICE
(
ID INT NOT NULL IDENTITY,
catagory VARCHAR(255) not null,
singlePrice FLOAT not null,
name VARCHAR(55) not null,
description VARCHAR(255) ,
PRIMARY KEY(ID)

)

CREATE TABLE S_ORDER
(
ID INT NOT NULL IDENTITY,
QUANTITY INT not null,
SERVICEID INT not null,
PRIMARY KEY(ID),
CONSTRAINT FK_SERVICE_ID FOREIGN KEY (SERVICEID) REFERENCES SERVICE(ID)
)

/*


CREATE TABLE STOCKTYPE
(
ID INT NOT NULL IDENTITY,
STOCKNAME VARCHAR(30),
SINGLEPRICE FLOAT,
QUANTITY INT,
CATAGORY VARCHAR(60),
PRIMARY KEY(ID)
)


CREATE TABLE STOCK
(
ID INT NOT NULL IDENTITY,
DATEOFSTOCK DATE,
EMPLOYEEID INT,
STOCKTYPEID INT,
PRIMARY KEY(ID),
CONSTRAINT FK_STOCKID_STOCK FOREIGN KEY (STOCKTYPEID) REFERENCES STOCKTYPE(ID),
CONSTRAINT FK_EMPLOYEE FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(ID)
)




*/